### ISSUE TITLE
PlayList/SearchBar input.

### ISSUE THREAD

**Issue by farishkash** [MikkelSandbag/codecademy-intensive-jammming#2]
https://github.com/MikkelSandbag/codecademy-intensive-jammming/blob/24fcd56f64c291e76ee3f2aa875fb6436d83d876/jammming/src/Components/App/App.js#L90

You should be able to read the props after the state has been to be brought in as the current input value of the form.

**Comment by MikkelSandbag** [comment]
In my initial attempt, I was only setting the state of searchTerm and playlistName to the empty string on submit (App.js, line 84 and 87), but this wasn't causing the value of the inputs to update when the savePlaylist() method is called, so that's why I added this line.
Would it be better to create a new method that gets called in savePlaylist() that handles this? Or is there another way?

**Comment by farishkash** [comment]
Something more in the lines of this. 

<Playlist
            playlistTracks={this.state.playlistTracks}
            playlistName={this.state.playlistName}  **<------ should be able to transfer this to the form** 
            handlePlaylistNameChange={this.handlePlaylistNameChange}
            onRemove={this.removeTrack}
            onSave={this.savePlaylist} />
        </div>

<input
          placeholder="New Playlist"
          onChange={this.props.handlePlaylistNameChange} 
          **value={this.props.playlistName}**
/>

**Comment by MikkelSandbag** [comment]
Oh, duh :P
For some reason I thought it wasn't a good idea to set an input's value attribute to something like that, but that makes a lot of sense. Thanks! I'll try that.
